### ISSUE TITLE
Error: CacheManagerStore is not a constructor

### ISSUE THREAD

**Issue by anchalkhandelwal** [theogravity/express-session-cache-manager#1]
I am unable to use 'import' for the library and i am importing the library as below code. I get an error saying 
"  store: new CacheManagerStore(cacheManager.caching({
         ^
TypeError: CacheManagerStore is not a constructor
"

`
var cacheManager = require('cache-manager')
var CacheManagerStore = require('express-session-cache-manager')

// storage for the cachemanager
var fsStore = require('cache-manager-fs');

// initialize caching on disk
 const sessionMiddleware = session({
   store: new CacheManagerStore(cacheManager.caching({
     store: fsStore,
     options: {
      ttl: 60*60 /* seconds */,
       maxsize: 1000*1000*1000 /* max size in bytes on disk */, 
      path:'diskcache', preventfill:true
     }
   }))
 })
app.use(sessionMiddleware)
`

**Comment by theogravity** [comment]
Your example is using require not import

You might need to do 

`var CacheManagerStore = require('express-session-cache-manager').default` if so
